"""Initial migration.

Revision ID: 231f3ceda1ae
Revises: 
Create Date: 2024-10-01 19:57:26.766399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231f3ceda1ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
